### ISSUE TITLE
Unit testing fails on OS/X

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#1205]
Getting this on all os/x builds, in all PRs:

```
======================================================================
FAIL: test_logging (test_opt_optimisation_controller.TestOptimisationController)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pints/pints/pints/tests/test_opt_optimisation_controller.py", line 127, in test_logging
    self.assertEqual(log_should_be, c.text())
AssertionError: 'Maxi[333 chars]0:00.0\n10    60    -4.140462   0:00.0\nHaltin[43 chars]d.\n' != 'Maxi[333 chars]0:00.1\n10    60    -4.140462   0:00.1\nHaltin[43 chars]d.\n'
Diff is 642 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
```

Anyone have a mac they can debug this with?

**Comment by chonlei** [comment]
This is fixed in #1206

**Comment by MichaelClerx** [comment]
Not quite fixed! But should be easier to debug now when it re-appears!

**Comment by chonlei** [comment]
Ha, yeah, not a fix, it appears again
```
======================================================================
FAIL: test_logging (test_opt_optimisation_controller.TestOptimisationController)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/pints/pints/pints/tests/test_opt_optimisation_controller.py", line 130, in test_logging
    self.assertEqual(log_should_be, c.text())
AssertionError: 'Maxi[333 chars]0:00.0\n10    60    -4.140462   0:00.0\nHaltin[43 chars]d.\n' != 'Maxi[333 chars]0:00.1\n10    60    -4.140462   0:00.1\nHaltin[43 chars]d.\n'
  Maximising LogPDF
  Using Exponential Natural Evolution Strategy (xNES)
  Running in sequential mode.
  Population size: 6
  Iter. Eval. Best      Time m:s
  0     6     -4.140462   0:00.0
  1     12    -4.140462   0:00.0
  2     18    -4.140462   0:00.0
  3     24    -4.140462   0:00.0
  6     42    -4.140462   0:00.0
- 9     60    -4.140462   0:00.0
?                              ^
+ 9     60    -4.140462   0:00.1
?                              ^
- 10    60    -4.140462   0:00.0
?                              ^
+ 10    60    -4.140462   0:00.1
?                              ^
  Halting: Maximum number of iterations (10) reached.


----------------------------------------------------------------------
Ran 591 tests in 131.479s

FAILED (failures=1, skipped=1)
##[error]Process completed with exit code 1.
```

**Comment by chonlei** [comment]
I definitely saw this before: https://github.com/pints-team/pints/pull/1175#issuecomment-662807319 :smile:
